# Generated by Django 3.2.15 on 2022-11-09 11:26

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=api.models.random_string_length_20, max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favourite_users_list', to='api.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
